### ISSUE TITLE
Feature: add support of local MSI package source

### ISSUE THREAD

**Issue by Tontonitch** [LordHepipud/icinga2-powershell-module#16]
Hello,
It is quite common that the MSI packages (or any other ressources) cannot be downloaded due to some security policies. So, that would be nice to have in this module the possibility to specify a directory where the MSI packages are stored.
I have modified the script for my usage, by disabling the download, changing the installer package. It works, but that would be great to have an option for such a feature.
BR,
Yannick

**Comment by LordHepipud** [comment]
I guess the best solution would be to allow the -DownloadURL parameter to contain a local path as well. In case the local path is set, the Agent will be installed from there and not beeing flushed.

Any objections?

**Comment by Tontonitch** [comment]
That is fine for me.
