### ISSUE TITLE
REST Api returning error

### ISSUE THREAD

**Issue by tocir** [LordHepipud/icinga2-powershell-module#17]
When testing REST Api using the following command.

`curl -H 'Accept: application/json' -u 'directoruser:directorpwd' https://server1.test.com/icingaweb2/director/host?name=wkstest1.test.com --insecure
`
Getting the following error.

`{ "error": "Failed to load icinga_host \"wkstest1.test.com\""
}`

Any ideas what can be causing this and a possible fix?
Thanks.

**Comment by LordHepipud** [comment]
Hello,

does the host wkstest1.test.com exist within the Icinga Director? If yes, could you please provide the current resolved configuration for the host (preview tab within the Icinga Director for the host object)?

Thank you in advance.

**Comment by LordHepipud** [comment]
Seems not to be an issue, as discussed here: https://monitoring-portal.org/index.php?thread/40436-icinga2-powershell-module-not-able-to-connect-to-director/

Closing this topic.
