### ISSUE TITLE
Icinga2 agent rollout script for Windows Server runs into an exception

### ISSUE THREAD

**Issue by t-rex2** [LordHepipud/icinga2-powershell-module#18]
Hi LordHepipud,

I have a problem with icinga2 agent rollout on Windows Server. After using your powershell script with admin rights...

PS C:\Windows\Temp> powershell.exe -executionpolicy unrestricted -file ".\Icinga2Agent-WINDOWSSERVER.ps1"

...the following exception comes up:

> Exception calling "fetchHostnameOrFQDN" with "0" argument(s): "Exception calling "setProperty" with "2" argument(s): "Exception calling "init" with "0" argument(s): "Exception calling "generateEndpointNodes" with "0" argument(s): "Exception calling "getEndpointConfigurationByArrayIndex" with "1" argument(s): "Cannot index into a null array."""""

I used your newest powershell script (Apr 10, 2017).

My settings inside the powershell script are (for better visualization I removed the ending quotes `):
$icinga = Icinga2AgentModule
    -ParentZone 'icinga2-master-zone'
    -ParentEndpoints 'icinga2a-master.localdomain', 'icinga2b-master.localdomain'
    -CAServer 'icinga2a-master.localdomain'
    -DownloadUrl 'https://icinga2a-master.localdomain/icinga2-agent/'
    -InstallAgentVersion '2.6.3'
    -FetchAgentFQDN $TRUE
    -DirectorUrl 'https://icinga2a-master.localdomain'
    -DirectorUser 'apiuser'
    -DirectorPassword 'test12345'
    -AllowUpdates $TRUE
$icinga.installIcinga2Agent()

The API-User on the Icinga2-Server has all rights.

/etc/icinga2/conf.d/api-users.conf
object ApiUser "apiuser" {
password = "test12345"
permissions = [ "*" ]
}

Is this exception a result of a bug? If you need more information I would be glad to assist you.

Best regards and thank you for your amazing sripts
Andrej

**Comment by LordHepipud** [comment]
Hello and thank you for the report. It indeed looks like a bug with the latest release.
What happens if you add the argument 

-EndpointsConfig

with as much blank strings ('') as endpoints configured with -ParentEndpoints?

In your provided example it would be:

-EndpointsConfig '', ''

Is the script running properly then? I will take some investiation on this and get back to you once I know more.

**Comment by LordHepipud** [comment]
I just played around with the script and I'm not receiving the error you are getting. Which Windows and PowerShell version are you using?

**Comment by LordHepipud** [comment]
Just applied a fix to the module I just realised. I renamed EndpointConfig to EndpointsConfig and forgot one line inside the code.

Can you please pull the module again and try if this fixes your problem?

**Comment by t-rex2** [comment]
Thank you so much for your fast investigation.

On Monday, when I will be back in office, I will try your new script. Afterwards I can give you a feedback.

Best regards
Andrej

**Comment by LordHepipud** [comment]
Hello,

any updates on this? Does the bug still occure?

**Comment by AHeinlein** [comment]
I just started to experiment with this module and ran into the same problem described here, using today's version of the module. The workaround describe with '-EndpointsConfig ","' did not help.

I am using Windows 7 Professional x64 with PowerShell 2.0

**Comment by LordHepipud** [comment]
This is weird because I can't seem to reproduce this issue. I will install Windows 7 here and test if I can figure out where this error comes from.

**Comment by AHeinlein** [comment]
I installed WMF 5.1 on this host and tried again, and the error went away. I am now facing different problems, but I can confirm this problem does not occur with PowerShell 5.1.

**Comment by t-rex2** [comment]
Hi everybody,

sorry for my late response. I was on vacation and before that I have not found time to pursue the topic further.

@LordHepipud: Yes, the bug still occur.

I will try to find some time for further investigation on my site. Perhaps I can limit the problem.

Best regards
Andrej

**Comment by vittel1** [comment]
I got the the same error. I guess it is a problem with the version of powershell.
It works with 4 and 5 but does not work with 2.

**Comment by AHeinlein** [comment]
So it seems we have narrowed down the problem. I feel I cannot help here any further; I usually live on the Unix side and have very little knowledge of powershell.

But it would be nice if you could give an estimate if that problem can be easily fixed. If not, I guess it would do no harm to declare this module to require PowerShell 4 or greater. I would then roll out WMF 5.1 to our windows machines.

**Comment by LordHepipud** [comment]
Just fixed the problem - thank you all for the research. The module will now work with PowerShell Version 2 as well. Didn't get the way I did the array checking wasn't properly possible with Version 2 (and it was quite ugly as well).

It will now work for any PowerShell Version
