### ISSUE TITLE
Support remote install

### ISSUE THREAD

**Issue by Hipska** [LordHepipud/icinga2-powershell-module#19]
After looking into the [readme](../blob/master/README.md), it seems not possible to install/setup Icinga2 agent on a remote system.

For Example, I want to install this module and some scripts on 1 central (Windows) server and then start installation/setup for multiple Windows clients. Currently, we need to install/deploy the module on every system and then run it.

**Comment by LordHepipud** [comment]
This is already possible with Windows tools. You can for example deploy the module over Group Policies on all Windows machines and trigger an initial run as well, or execute the module with PowerShell Remote Execution.

Build-in remote execution is not intended from my side, as this would cause an overhead and the functionality is already present with existing tools.

**Comment by Hipska** [comment]
Indeed, I figured out the possibility of PowerShell remote. But indeed, the module still needs to be deployed on every system.

**Comment by LordHepipud** [comment]
I believe in case Group Policies are not working to deploy the script, you might be able to copy the script over with remote execution and trigger it afterwards. Haven't tested this however.

But as PowerShell remote execution offers a huge range of features, this should be possible.
