### ISSUE TITLE
"hasConfigChanged" Exeception with Powershell Version 2

### ISSUE THREAD

**Issue by vittel1** [LordHepipud/icinga2-powershell-module#21]
Hi,

you fixed the error with the NULL-Array. This works now for me. 

Now I got a new error:

Exception calling "applyPossibleConfigChanges" with "0" argument(s): "Exception calling "hasConfigChanged" with "0" argument(s): "Exception calling "getHashFromString" with "1" argument(s): "The variable '$result' cannot be retrieved because it has not been set."""

The error appears only with Powershell Version 2 (4 & 5 works). Maybe another bug?

**Comment by LordHepipud** [comment]
Gonna take a look on that. Actually I haven't received this error before and I know plenty of environments with PowerShell version 2 for which the versions without the config endpoints worked before.

I will take a look on this. Could you please provide me with the arguments you are using for the config?

Thank you in advance!

**Comment by vittel1** [comment]
Here are the arguments I use:
```
   -FetchAgentFQDN       $TRUE `
    -DirectorUrl          'https://hostname.desy.de' `
    -DirectorUser         'fetchticketuser' `
    -DirectorPassword    'passwort' `
    -ParentZone      'master' `
    -ParentEndpoints 'hostname.desy.de' -EndpointsConfig 'hostname.desy.de;5665'`
    -CAServer        'hostname.desy.de'
```
I call the script with a batch script:
`powershell.exe -ExecutionPolicy Bypass -NoProfile -File "%~dp0IcingaPowershell.ps1`

Powershell Version:
```
PS H:\> $PSVersionTable
Name                           Value                                                                                                               
----                           -----                                                                                                               
CLRVersion                     2.0.50727.5485                                                                                                      
BuildVersion                   6.1.7601.17514                                                                                                      
PSVersion                      2.0                                                                                                                 
WSManStackVersion              2.0                                                                                                                 
PSCompatibleVersions           {1.0, 2.0}                                                                                                          
SerializationVersion           1.1.0.1                                                                                                             
PSRemotingProtocolVersion      2.1
```

If you need other information, let me know. Thanks for the quick answer!

**Comment by LordHepipud** [comment]
Was the agent already installed and configured before? Just wondering so I can try to re-create your issue.

**Comment by vittel1** [comment]
Yes, the agent is already installed.

For me it works when I add the following line: 

`$result = ""`

In this block:

```
    $installer | Add-Member -membertype ScriptMethod -name 'getHashFromString' -value {
        param([string]$text)
        $algorithm = new-object System.Security.Cryptography.SHA1Managed
        $hash = [System.Text.Encoding]::UTF8.GetBytes($text)
        $hashInBytes = $algorithm.ComputeHash($hash)
        $result = ""
        foreach($byte in $hashInBytes) {
             $result += $byte.ToString()
        }
        return $result;
}
```
Maybe thats helpful for you.

**Comment by LordHepipud** [comment]
'-.-

It looks like I forgot to initialize the variable before, that's why the output is undefined. I'm just wondering on why I'm not receiving this error on my test setup with PowerShell version 2. I will fix this asap.

Sorry!

**Comment by LordHepipud** [comment]
I just applied the fix - sorry for the misstake and thank you for the report and fix!
