### ISSUE TITLE
Add Support for Windows Core Server

### ISSUE THREAD

**Issue by HpotsirhcH** [LordHepipud/icinga2-powershell-module#23]
Right now the module is not able to run properly on Windows Core Server.

e.g. you have to install the .nupkg instead of the MSI file.

**Comment by LordHepipud** [comment]
I just installed Windows 2016 Core Server within my demo environment and the MSI installer and the module were working fine.
Are you maybe talking about the NANO server?

**Comment by HpotsirhcH** [comment]
Yes you are right. The msi and module work fine. I tested again.
