### ISSUE TITLE
Module returns "0" even when installation failed

### ISSUE THREAD

**Issue by widhalmt** [LordHepipud/icinga2-powershell-module#39]
We forgot to provide some information (e.g. `-InstallAgentVersion` ) so the module was not able to install the agent. The script exited with code `0` nonetheless.

**Comment by LordHepipud** [comment]
The main problem with that is that the module capable of doing quite more than installing the Agent. Determining on when to throw an exception is not that simple, as it could be intendened to simply write configuration or installing the NSClient++, without touching the Icinga 2 Agent at all.

I will try to figure something out for this.

**Comment by widhalmt** [comment]
Maybe you could add a "NoAgentInstallation" flag? I'd suggest the negated form to not break backwards compatibility.

**Comment by widhalmt** [comment]
That way you could check wether not installing is what the user wanted or if it just was an error.

**Comment by rustyricky** [comment]
Maybe you could implement PowerShell's Common Parameters (https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/about/about_commonparameters) or more specifically the `-ErrorAction` Parameter and decide whether to cancel the setup with exit code 1 or continue when encountering an error based on it's setting.

The official ErrorAction behaviours are

```
Continue
Ignore
Inquire
SilentlyContinue
Stop
Suspend
```

**Comment by LordHepipud** [comment]
Made some additional changes and reverted the exception output in case the installation failed.

Reason: The download URL is defined by default and is not a valid check-source, `-InstallAgentVersion` can be left without content, as users might not wish to install the Agent but to configure it.

The `-ErrorAction` argument is not a proper solution, as on which state I'm going to throw an error or not?

I suggest a solution like from @widhalmt would be required, adding an additional argument by default to throw an error in case the Agent can not be installed. Still I'm not happy with that, is it will increase the complexity of the module.

In case the Agent version is not configured, the script will now write a warning:

`Warning: Icinga 2 Agent will not be installed. Argument -InstallAgentVersion is not defined.`

**Comment by LordHepipud** [comment]
Another possible solution: Remove default configured `-DownloadUrl` value. In that case printing an exception in case the `-InstallAgentVersion` argument is not set would be valid, because the second required argument is not defined.

**Comment by LordHepipud** [comment]
Re-considered this issue and discussed it internally. I will update the documentation to make clear `-InstallAgentVersion` is required to be defined in order to install the Icinga 2 Agent. I will however not throw an error or exit the Script with Exit Code 1, as this could be intended from user side. Warnings are however printed and visible within the logfile if enabled (or the console itself)
