### ISSUE TITLE
Allow for using a full path including filename for installation

### ISSUE THREAD

**Issue by widhalmt** [LordHepipud/icinga2-powershell-module#40]
Some software management tools could use the module more easily when you could provide them with the full path to the .msi package. e.g. `C:\install\icinga.msi`. This would make giving the version number obsolete.

**Comment by LordHepipud** [comment]
The only problem I see with this feature would be that I won't be able check the current installed version of Icinga against the wanted version. Right now the script will skip in case the same version is already installed.

For this some further adjustments would be required to prevent the module of installing the same version again (just in case users wand to update the Agent)

**Comment by LordHepipud** [comment]
I have thought about this feature request and in my oppinion it would increase the complexity of the module. Shipping the correct installer version with the architecture and the version string as they are provided by the Icinga Team are valid and the version string allows me to check properly against the installed version (if there is one) in case updates are required.
