### ISSUE TITLE
Allow configuration of installation path

### ISSUE THREAD

**Issue by widhalmt** [LordHepipud/icinga2-powershell-module#43]
A customer of mine wants to install the agent to another Windows drive than C: . Please add a way to set the path where the agent is installed.

**Comment by LordHepipud** [comment]
As far as I can tell the Icinga 2 Agent installer is not supporting this feature. Could you please open an issue on the Icinga 2 project and reference this issue please?

**Comment by LordHepipud** [comment]
Made some research on the MSI file and the required argument is 'INSTALL_ROOT'

**Comment by LordHepipud** [comment]
Agent install directory can now be configured. In addition, the current installation directory will remain intact and the agent will be updated into this directory. During updates / downgrades the Agent can be installed into a different directory now.
