### ISSUE TITLE
Uninstallation leaves NSClient untouched

### ISSUE THREAD

**Issue by widhalmt** [LordHepipud/icinga2-powershell-module#44]
Even when using `-FullUninstallation` the previously installed NSClient++ is not uninstalled during the uninstallation.

Could you add a switch that allows for uninstalling the NSClient?

**Comment by widhalmt** [comment]
A problem could be that the NSClient seems to need a reboot after uninstallation. Should we try to handle this in the PS Module or talk to Michael about changing the NSClient (un)installer?

**Comment by LordHepipud** [comment]
The problem is that I'm unable to locate any details about the NSClient within the registry. Unlike Icinga 2, the informations stored there do not cover the informations I need.

That's why the NSClient++ is left untouched because I'm unable to provide a proper solution for this at the moment.
