### ISSUE TITLE
Script run should without error in case Template Key is no longer present

### ISSUE THREAD

**Issue by LordHepipud** [LordHepipud/icinga2-powershell-module#49]
Re-Write code base for handling API-Keys and Host-Creation to ensure the script will run even when the template key is no longer present or valid.

**Comment by Thomas-Gelf** [comment]
With a given Host-Key the normal run should involve just a single call to `self-service/powershell-parameters` based on the Host key. Usually this will succeed, parameters should be applied, all done. Just in case there is no host key or the request with the host key failed, a new host registration should be performed.

**Comment by LordHepipud** [comment]
Fixed with link commit. The Host-Token is now prefered over the Template token and is checked first before doing anything else.
In case the Host token is no longer valid, you will receive an info about this. In case the Template token is still configured, the module will proceed and try to re-claim the host object and store the new host token locally.

In case both tokens are not set or the host token is invalid and no template token is defined, the module will try to continue with basic handling, but will not change configuration as the arguments are not fetched.

This should improve the overall communication with the Director API, as status codes are now handeled as well, informing the user of the module what kind of problem might have occured.
