### ISSUE TITLE
Change Icinga LogOn User with modifyIcingaServiceUser

### ISSUE THREAD

**Issue by vittel1** [LordHepipud/icinga2-powershell-module#51]
Hey,

maybe you could help me out with the method of the IcingaServiceUser. I want to change the Log On User to the LocalSystem-User.

`$icinga = Icinga2AgentModule -IcingaServiceUser    'HOSTNAME\LocalSystem' `

I have tried some different versions but I always get this error output, and the Log On User does not change:

> Notice: Updating Icinga 2 service user to HOSTNAME\LocalSystem
> Error: DESCRIPTION:        Modifies a service entry in the registry and Service Database.USAGE:        sc <server> config [service name] <option1> <option2>...OPTIONS:NOTE: The
>  option name includes the equal sign.      A space is required between the equal sign and the value. type= <own|share|interact|kernel|filesys|rec|adapt> start= <boot|system|aut
> o|demand|disabled|delayed-auto> error= <normal|severe|critical|ignore> binPath= <BinaryPathName> group= <LoadOrderGroup> tag= <yes|no> depend= <Dependencies(separated by / (for
> ward slash))> obj= <AccountName|ObjectName> DisplayName= <display name> password= <password>

**Comment by LordHepipud** [comment]
What happens if you specify the user like this:

```powershell
$icinga = Icinga2AgentModule -IcingaServiceUser 'LocalSystem'
```

This is the default behaviour and should work. The domain or host-domain is not required in this case. Does this resolve the issue?

**Comment by vittel1** [comment]
Hey,
still not work for me with:
`$icinga = Icinga2AgentModule -IcingaServiceUser    'LocalSystem' `

Same error output like before and the service user is still the Network Service Account.
Why did he say that he successfully updated it but nothing changes?

> Notice: Updating Icinga 2 service user to LocalSystem

**Comment by LordHepipud** [comment]
This is weird. What happens if you open a command prompt as admin and type in the following:

```
sc.exe config icinga2 obj="LocalSystem"
```

Is the service updated successfully afterwards?

**Comment by vittel1** [comment]
Sorry for the late response. I get this output:

> C:\Windows\system32>sc.exe config icinga2 obj="LocalSystem"
> DESCRIPTION:
>         Modifies a service entry in the registry and Service Database.
> USAGE:
>         sc <server> config [service name] <option1> <option2>...
> 
> OPTIONS:
> NOTE: The option name includes the equal sign.
>       A space is required between the equal sign and the value.
>  type= <own|share|interact|kernel|filesys|rec|adapt>
>  start= <boot|system|auto|demand|disabled|delayed-auto>
>  error= <normal|severe|critical|ignore>
>  binPath= <BinaryPathName>
>  group= <LoadOrderGroup>
>  tag= <yes|no>
>  depend= <Dependencies(separated by / (forward slash))>
>  obj= <AccountName|ObjectName>
>  DisplayName= <display name>
>  password= <password>

**Comment by LordHepipud** [comment]
This is interesting. So it's not really a bug within the PowerShell Module, as it uses the same command which *should* work in first place.

Which operating system are you using including the PowerShell version?

Just type

```powershell
$PSVersionTable.PSVersion
```

within a PowerShell and execute the command.

**Comment by vittel1** [comment]
I am using a Windows 7.

> PS C:\Windows\system32> $PSVersionTable.PSVersion
> 
> Major  Minor  Build  Revision
> 4      0      -1     -1

**Comment by LordHepipud** [comment]
I will setup a Windows 7 machine and test the command there.

Which version exactly?
Professional, Enterprise, ... ?

**Comment by vittel1** [comment]
It is an Enterprise Version. Thanks for your help!

**Comment by vittel1** [comment]
Do you have any news about this yet? :)

**Comment by Copis** [comment]
Hi

In order to change LogOn user into a service I used this into powershell:
`# Change icinga2 service account`
`Stop-Service -Name 'Icinga2' -Verbose`
`sc.exe config "Icinga2" obj= "LocalSystem"`
`Start-Service -Name 'Icinga2' -Verbose`

I tested it on W7, W8, W8.1, W10, 2008R2, 2012 and 2012R2

**Comment by vittel1** [comment]
That works for me! Thanks! :)

**Comment by LordHepipud** [comment]
Hello,

sorry for my late response. I entirely forgot to update this issue. I think I found the problem, as I'm always adding the "password" argument instead of skipping it if not required.

Working on a fix for this already. Sorry again for the long wait time!
