### ISSUE TITLE
Use the Icinga 2 standard config paths for config deployment on Windows

### ISSUE THREAD

**Issue by dnsmichi** [LordHepipud/icinga2-powershell-module#52]
## Expected Behavior

Use the default paths and configuration files as proposed by the Windows package for Icinga 2.

## Current Behavior

Putting everything into the `icinga2.conf` makes debugging a Windows client harder, as it does not follow the official documentation. I've seen it today in a support case, it costs plenty of time to find out where things are stored.

It also breaks supported CLI commands such as `icinga2 feature enable debuglog`.

## Possible Solution

Please enable users to use the proposed standard paths of the Icinga 2 Windows package:

- Only include directives inside `icinga2.conf` (leave it as is, or just remove "conf.d" inclusion - see icinga/icinga2#5426 and icinga/icinga2#3246)
- Populate zone and endpoint details into `zones.conf`. Keep in mind that Icinga 2 v2.7.0 automatically provides `director-global` and `global-templates` by default inside the `zones.conf` file (see icinga/icinga2#5106 for details)
- Enable the default features on an agent (`main-log` should be sufficient, optional: `checker` for config sync, not command_endpoint)
- Include `features-enabled` in `icinga2.conf` and allow to use the documented CLI command `icinga2 feature <list|enable|disable>`
- Update `features-available/api.conf` with specified settings, i.e. `accept_config` and `accept_commands`
- Update `constants.conf` when needed, i.e. setting the NodeName constant

The received certificates are correctly stored in SysconfDir + "/icinga2/pki/" + NodeName ... already. It would be nice to see anything else also put into the default paths as documented everywhere.

Specifically this would need rewrites in `generateIcingaConfiguration` and remove the config blob.

If it is about config validation and a possible rollback (this seemed to be the main argument months ago):

- Deploy the configuration into a temporary directory, like %ProgramData%\ICINGA2\tmp
- Run a config validation with changed paths: `icinga2.exe daemon -C -DSysconfDir= %ProgramData%\ICINGA2\tmp
- If successful, change the copy target to "production"

This would likely need just one config deployment function, which has a target as parameter (test or prod) and checks against their validation. Then you can do a rollback more easily (i.e. don't copy anything in case of a failure).

If you need cli and config rendering examples, you can look into the `icinga2 node wizard` or `icinga2 node setup` CLI code.

https://github.com/Icinga/icinga2/blob/master/lib/cli/nodesetupcommand.cpp
https://github.com/Icinga/icinga2/blob/master/lib/cli/nodewizardcommand.cpp

Since we've seen that today:

```
if (!globals.contains("NscpPath")) {
  NscpPath = dirname(msi_get_component_path("{5C45463A-4AE9-4325-96DB-6E239C034F93}"))
}
```

is not needed, that is already done inside `include <nscp>` and will never be evaluated.

**Comment by LordHepipud** [comment]
As discussed already, for config validation and 100% availability of the Agent, the way it is know is the best possible.
I have added a documentation part in the configuration file itself, explaining arguments and the content.

The support case you discussed was in no way responsible for the complexity or the error handling and in case of a support call, having one simple file containing all information is alot easier for debugging.

I would consider extending the Icinga 2 documentation, explaining the PowerShell Module behaviour regarding the configuration.

Best regards

**Comment by dnsmichi** [comment]
I strongly disagree here. This should conform the paths and specifications inside the Icinga stack. Documentation might be a solution, the real solution is to fix the Powershell module and its paths to follow the default client installation.

We should discuss this with @lippserd and @bobapple once this Powershell module should be included in the Icinga stack and Icinga 2 package.

**Comment by LordHepipud** [comment]
I discussed this topic with @lippserd already and he agrees that the way it is can be kept as it is a working solution.

**Comment by lippserd** [comment]
Yep, it is true that I agreed to leave it as it is for the moment. It is simply working and we have low to no noise from the community with this module. Especially in this regard. But Michael talked to me again about this issue and I must agree with him that it makes sense to tackle this issue in the long term. We should join efforts to make products from Icinga and products in the Icinga ecosystem as homogeneous as possible. I think we guys should pour some oil on troubled waters here, get some beers and discuss that.

**Comment by NeverUsedID** [comment]
*Community making some Noise* :)

Thanks @dnsmichi for pointing me here. 

The thing with the community noise: I think the real power of the module is hard to see at the beginning. I needed some time to see how powerfull it is. I will write a small howto when I find the time. I use it to add any Windows server by just executing the script on a new deployed Server. It also adds Disks, OS Version etc.  

So, its by far the easiest way to add a Windows Host, if you don't have something like Ansible.
