### ISSUE TITLE
Option 'DownloadUrl' not being applied when using Self-Service API

### ISSUE THREAD

**Issue by killepitisch** [LordHepipud/icinga2-powershell-module#53]
Hi,

when using the Director Self-Service API (-DirectorUrl 'http://xxx') it is not possible to apply a custom location for the installer package (-DownloadUrl 'http://yyy') at the same time. Regardless of which value is being set as URL always the default value 'https://packages.icinga.com/windows/' is being used as location.

**Comment by LordHepipud** [comment]
Hello

You have to configure your Director Self-Service API for the download URL, as all data is fetched from there while using it.

The documentation describes the path to it: https://github.com/Icinga/icinga2-powershell-module/blob/master/doc/20-Automation.md

Best regards

**Comment by killepitisch** [comment]
@LordHepipud Thanks a lot, will try that out.
