### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by tupcakes** [LordHepipud/icinga2-powershell-module#55]
I'm trying to get the module installed on server 2016, but I keep getting the following error when I try and run the command.

Icinga2AgentModule : The term 'Icinga2AgentModule' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:11
+ $icinga = Icinga2AgentModule `
+           ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Icinga2AgentModule:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The module has been placed here: C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Icinga2Agent

It also shows up when doing a get-module -listavailable with the Icinga2AgentModule listed as the only exported command. However when I import the module Icinga2Agent it shows no exported commands. I'm not sure what I'm missing.

**Comment by LordHepipud** [comment]
Can you please navigate into the module directory and locate the file Icinga2Agent.psd1

Once found, simply delete it and re-open your PowerShell instance.

Does it work now?

**Comment by tupcakes** [comment]
Yep that did it. Thanks.
