### ISSUE TITLE
Some issues with older servers running 2008R2 - Powershell 2

### ISSUE THREAD

**Issue by Insurgentes** [LordHepipud/icinga2-powershell-module#56]
I am using a custom ps1 and the Icinga2Agent.psm (not current but older one) are in C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Icinga2Agent\

I checked the other hint to delete the psd from other recent issue but I don't have that file. I have a batch script (with remotesigned or unrestricted) that copies my ps1 and the psm file to the location above. This works on nearly all my servers but when I have to use an older one (windows server 2008R2) with powershell 2 I get:

The term 'Icinga2AgentModule' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Icinga2Agent\Icinga.ps1:95 char:29
+ $icinga = Icinga2AgentModule <<<<  `
    + CategoryInfo          : ObjectNotFound: (Icinga2AgentModule:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Doesn't happen with my machines that have more recent powershell. Any ideas?

**Comment by mikeyfreshh** [comment]
![image](https://user-images.githubusercontent.com/7351492/31624163-be222490-b26f-11e7-92e9-ca917eff01d6.png)

I have the same issue on all my servers, including 2008 R2 and 2012.  I've tried the master and next branches and both give the same result.  I've also tried installing the module to each path listed and none of them work.

**Comment by LordHepipud** [comment]
@mikeyfreshh : There is an issue right now in case the .psd1 file is included within the module directory. Once deleted, the module should work on most systems. I will have to remove the file form the repo to ensure the problem does not appear. Does this resolve your issue?

@Insurgentes What happens if you install the module to the currently logged in user within the 'private' repository? Does this work for the system or do you receive the same issue? If you use
```powershell
Get-Module -ListAvailable
```

Is the module showing up there? Is your path

> C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Icinga2Agent\

also mentioned somewhere within that list?

**Comment by Insurgentes** [comment]
@LordHepipud I installed the module in c:\program files\windowspowershell\modules\Icinga2Agent and imported the module after setting this as a path certified for module usage.  I think it's ok but have errors:
Next issue is how do I use JSON functionality with Powershell2 as I can't use ConvertTo-Json with powershell2?

**Comment by LordHepipud** [comment]
Does the module show up somewhere by using:

```powershell
Get-Module -ListAvailable
```

For the JSON part: If you wish to send JSON data directly to the Director for creating object, you will have to write the JSON-String yourself. Something like:
```json
{
    "imports":      "generic-host",
    "object_type":  "object",
    "display_name": "Example Host",
    "address":      "127.0.0.1",
    "object_name":  "Example Host"
}
```

Hope this helps.

**Comment by Insurgentes** [comment]
@LordHepipud 

Will check re JSON, thanks a lot for your help!

I think for the module it's fine, I created the program files location as stated and import.

Much less hassle with PowerShell > V2

**Comment by LordHepipud** [comment]
Ì have played around with that for some time now on different systems and I'm not having this kind of issue. I'm not quite sure where to start digging here to reproduce it.

**Comment by LordHepipud** [comment]
Is this issue still occuring or is it resolved? I was unable to reproduce.
The .psd file has been removed from the repo already ('next' branche right now), to ensure a proper usage within all environments.

**Comment by LordHepipud** [comment]
I found the issue regarding your setup. In order for the module to work in PowerShell 2 environments, you will have to import the module first with

```powershell
Import-Module Icinga2Agent;
```

So a script call could look like this:

```powershell
Import-Module Icinga2Agent;
$icinga = Icinga2AgentModule <arguments here> `
               -RunInstaller;
```

**Comment by LordHepipud** [comment]
I have extended the documentationfor this special case within PowerShell version 2 environments: https://github.com/Icinga/icinga2-powershell-module/blob/master/doc/02-Installation.md
