### ISSUE TITLE
script not resolve dns name to IP

### ISSUE THREAD

**Issue by orciniusorsa** [LordHepipud/icinga2-powershell-module#58]
HI,
The script createa in Icinga Director an host without IP.
the full domain name is written in the host address field.

i use script with self service API.

**Comment by LordHepipud** [comment]
Hello,

can you please provide a screenshot of your self-service API and the arguments you are handing over the function call?

Can you also please post the log output?

Are you using the 'master' or 'next' branche?

**Comment by orciniusorsa** [comment]
hi 
thank for yuor answer

1. i`m use master branch

2. screenshot my self-service API
![image](https://user-images.githubusercontent.com/14977624/32480886-f7f57b5c-c3a1-11e7-91ce-45e8ddbf464a.png)

3. argument function call
$icinga = Icinga2AgentModule `
              -DirectorUrl       'https://icinga2-master.example.com/icingaweb2/director/' `
              -DirectorAuthToken '34086b3480965b083476c08346c34980'

$icinga.installMonitoringComponents();
it use from 
https://github.com/Icinga/icinga2-powershell-module/blob/master/doc/20-Automation.md

4. log
PS C:\Windows\system32> $icinga.installMonitoringComponents();
Notice: Setting internal Agent Name to SRV0
Notice: Trying to fetch Host IP-Address for hostname: SRV0
Notice: Creating host SRV0 over API token inside Icinga Director.
Warning: Icinga 2 Agent does not seem to be installed on the system
Notice: Downloading Icinga 2 Agent Binary from https://packages.icinga.com/windows/Icinga2-v2.7.1-x86_64.msi  ...
Warning: Icinga 2 Agent Installer verification disabled.
Notice: Installing Icinga 2 Agent
Notice: Icinga 2 Agent installed.
Notice: Removing downloaded Icinga 2 Agent installer
Notice: Writing host API-Key "<.....>" to "C:\ProgramData\icinga2\etc\icinga2\icingadirector.token"
Notice: Generating Icinga 2 certificates
Notice: information/base: Writing private key to 'C:\ProgramData\icinga2\etc\icinga2\pki\SRV.key'.
information/base: Writing X509 certificate to 'C:\ProgramData\icinga2\etc\icinga2\pki\SRV0.crt'.
Notice: Storing Icinga 2 certificates
Notice: information/pki: Writing certificate to file 'C:\ProgramData\icinga2\etc\icinga2\pki\trusted-master.crt'.
Notice: Certificate fingerprint: <...>
Warning: CA fingerprint validation disabled
Notice: Requesting Icinga 2 certificates
Notice: information/cli: Writing signed certificate to file 'C:\ProgramData\icinga2\etc\icinga2\pki\SRV03.difco.local.cr
t'.
information/cli: Writing CA certificate to file 'C:\ProgramData\icinga2\etc\icinga2\pki\ca.crt'.
Notice: Icinga 2 configuration backup successfull
Notice: Writing icinga2.conf to C:\ProgramData\icinga2\etc\icinga2\
Notice: Icinga 2 configuration check successfull.
Notice: Trying to disable debug log for Icinga 2...
Notice: Icinga 2 debug log is not enabled or configuration not found
Notice: Trying to install Icinga 2 Agent Firewall Rule for port 5665
Notice: Icinga 2 Agent Firewall Rule successfully installed for port 5665
Notice: Trying to install NSClient++ from C:\Program Files\ICINGA2\sbin\NSCP.msi
Notice: NSClient++ successfully installed.
Notice: Trying to remove NSClient++ Firewall Rule...
Notice: NSClient++ Firewall Rule has been successfully removed
Notice: Trying to remove NSClient++ service...
Notice: NSClient++ Service has been removed
Notice: Restarting service icinga2...
Notice: Icinga 2 Agent successfully restarted.
0

**Comment by LordHepipud** [comment]
In general this should work. What happens if you try using

```
nslookup SRV0
```

(Replace SRV0 with your actual hostname)

from a command line. What output do you receive there?

**Comment by orciniusorsa** [comment]
Hi
comman execute on server SRV0
PS C:\Windows\system32> nslookup srv0
Server:  dc0.co.al
Address:  10.2.2.80

Name:    srv0.co.al
Address:  10.2.2.176

PS C:\Windows\system32> nslookup srv0.co.al
Server:  dc0.co.al
Address:  10.2.2.80

Name:    srv0.co.al
Address:  10.2.2.176

**Comment by LordHepipud** [comment]
This is weird. Can you please try using the 'next' branche of the module and try again? I have made some re-writes to the entire handling there which should work properly.

A release is planned by the end of this week for the final version anyway.

Thank you in advance.

**Comment by LordHepipud** [comment]
This should be fixed on the 'next' branche already. If not please re-open this issue.

**Comment by orciniusorsa** [comment]
hi,
i wait for the next branch.
thank you for your work!

**Comment by LordHepipud** [comment]
I made a release in the meantime already :D
Please try the 1.0.0 version - everything should work fine there ^^
