### ISSUE TITLE
IcingaServiceUser Parameter doesn't work

### ISSUE THREAD

**Issue by Gammenon** [LordHepipud/icinga2-powershell-module#68]
Hi,

while evaluating the powershell module i encountered some unexpected behavior. 
Wenn leaven out the -IcingaServiceUser parameter the default value should be LocalSystem. After a generally successfull run the service user is set to "Network Service".

If I set the parameter (-IcingaServiceUser 'LocalSystem') I  get an error:

`Error: DESCRIPTION:        Modifies a service entry in the registry and Service Database.USAGE:        sc <server> config [service name] <option1> <option2>...OPTIONS:NOTE: The option name
 includes the equal sign.      A space is required between the equal sign and the value. type= <own|share|interact|kernel|filesys|rec|adapt> start= <boot|system|auto|demand|disabled|delaye
d-auto> error= <normal|severe|critical|ignore> binPath= <BinaryPathName> group= <LoadOrderGroup> tag= <yes|no> depend= <Dependencies(separated by / (forward slash))> obj= <AccountName|Obje
ctName> DisplayName= <display name> password= <password> 
`
a look into the sc.exe documentation as well as the message it self tells me, a blank is missing after the equal sign. So I modified:

Line 1309:
```
- $result = $this.startProcess('sc.exe', $TRUE, [string]::Format('config icinga2 obj="{0}"{1}', $newUser, $password));
+ $result = $this.startProcess('sc.exe', $TRUE, [string]::Format('config icinga2 obj= "{0}"{1}', $newUser, $password));
```

Line 1329:
```
- $result = $this.startProcess('sc.exe', $TRUE, [string]::Format('config icinga2 obj="{0}"{1}', $currentUser.StartName, $password));
+ $result = $this.startProcess('sc.exe', $TRUE, [string]::Format('config icinga2 obj= "{0}"{1}', $currentUser.StartName, $password));
```
			
Line 1333:			
```
- $result = $this.startProcess('sc.exe', $TRUE, 'config icinga2 obj="LocalSystem" password=dummy');
+ $result = $this.startProcess('sc.exe', $TRUE, 'config icinga2 obj= "LocalSystem" password= dummy');
```
After that, the parameterized run worked out fine but the unparameterized run still doesn't set the script defined default user. So there ist still something wrong I didn't recognize.

I would appreciate if someone else could have another look at this.

**Comment by LordHepipud** [comment]
Thank you for the report and digging into the problem.

That is interesting, because on some systems the arguments as provided are working. I will add the blank space into the module - thank you.

For the service user: In case the argument is not specified, the module will not execute the function for changing the user. I might have also documented the default Icinga 2 User for the service wrongly.

Which default user are you expecting to be set on the Agent?

**Comment by Gammenon** [comment]
I expected the default as described in the documentation in the module source code (LocalSystem (Icinga default)). So i expected if I set nothing at all, LocalSystem would be set. 

But by now I suspect that I have misunderstood this description and LocalSystem is the default if the parameter is called without an explicit user behind

```
        # Agent installation / update
        <# This argument will allow to override the user the Icinga 2 service is running with. Windows provides some basic users already which can be configured:

        LocalSystem (Icinga default)
        NT AUTHORITY\NetworkService
        NT AUTHORITY\LocalService
        If you require an own user, you can add that one as well for the argument. If a password is required for the user to login, seperate username and password with a ':'.

        Example: jdoe:mysecretpassword

        Furthermore you can also use domains in combination and pass them over.

        Example: icinga\jdoe:mysecretpassword[string]$IcingaServiceUser,
        #>
        [string]$IcingaServiceUser,
```

perhaps blank or no blank depends on the OS or sc.exe Version
Mine is 6.1.7600.16385 from the sc.exe properties on a Windows Server 2008 R2

**Comment by LordHepipud** [comment]
In general the Icinga user is set during installation already, but I'm not sure if the specification I added with LocalSystem is correct.

I will review this and correct it in case I was misstaken here.
