### ISSUE TITLE
Create/Modify constants via Parameter

### ISSUE THREAD

**Issue by freddy4711** [LordHepipud/icinga2-powershell-module#70]
Hi,

first of all, the module is great. Thank you very much for this very useful tool.

I have a feature request for the module. It would be nice if there is a possiliblity to add or modify constants with the powershell module. 

We are using the "CustomPluginDir=" constant which I need reconfigure after the installation.

**Comment by LordHepipud** [comment]
As we are moving forward with Icinga for Windows and the PowerShell Framework, we will not continue on this issue.
