### ISSUE TITLE
Add option to create host "disabled"

### ISSUE THREAD

**Issue by widhalmt** [LordHepipud/icinga2-powershell-module#71]
Hi,

Could you add an option to have new hosts added as "disabled" in Director? I have a customer who imports hosts during setup but wants to start monitoring after some extra steps are finished. Having the host from the start is a good thing so the monitoring admins can make changes, add templates, etc. but the host might not be ready for monitoring, yet.

Cheers,
Thomas

**Comment by LordHepipud** [comment]
Hello,

In general this would be possible with a simple argument, beeing passed as JSON to the host creation or by specifiying a custom JSON Object.
It depends however how the host is created.

If you are using the module with user / password - it would be no problem at all.
In case you are using the SelfService API from the Director, it will not be possible as the Director is not allowing this kind of argument and dropping the request. Furthermore it would not be possible to pass the argument properly.

So I see two steps here:
* Include this feature into the PowerShell Module with an argument
* Extend the IcingaDirector SelfService API with an option to create disabled host objects

Any further suggestions?

**Comment by widhalmt** [comment]
Since the setup which gave me the idea is using the self-service API a lot I'll open an according issue Director.

**Comment by LordHepipud** [comment]
As we are moving forward with Icinga for Windows and the PowerShell Framework, we will not continue on this issue.
