### ISSUE TITLE
Powershell module fails if using https also while IgnoreSSLErrors is set

### ISSUE THREAD

**Issue by dgoetz** [LordHepipud/icinga2-powershell-module#72]
Powershell module fails to get the API version from the director using the self service API if using https also while IgnoreSSLErrors is set, when disabling the rewrite from http to https and using http it works as expected. So it seems  
`[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }` is not enough (or not enough in all cases) to disable certificate validation.

**Comment by LordHepipud** [comment]
I have tested this issue within a  testing environment with @dgoetz and we both were unable to reproduce this issue.

A commit to improve the output on debug mode has been made and might give further details on why this error occures. The current implementation should cover all possible SSL errors.

**Comment by rajo** [comment]
I've checked out master and tried to execute it once via an https-URI and once via http - Output attached. The http-Version correctly installs everything.

[Debug_with_ssl.txt](https://github.com/Icinga/icinga2-powershell-module/files/1793117/Debug_with_ssl.txt)
[Debug_without_ssl.txt](https://github.com/Icinga/icinga2-powershell-module/files/1793118/Debug_without_ssl.txt)

**Comment by LordHepipud** [comment]
This is weird. I have no idea on why there is an unexpected error returned.

Could you please try the following:

Locate:
```powershell
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
```

Above this line, please add the following

```powershell
$SSLProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12';
[System.Net.ServicePointManager]::SecurityProtocol = $SSLProtocols;
```

The result should look like this:

```powershell
if ($this.config('ignore_ssl_errors')) {
    $SSLProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12';
    [System.Net.ServicePointManager]::SecurityProtocol = $SSLProtocols;
    [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
}
```

Can you please try then again with SSL and post back the result?

**Comment by rajo** [comment]
Okay, I think I've found the culprit - security :)

This is the output
`Notice: Started script run...
Fatal: Ausnahme beim Aufrufen von "getIcingaDirectorVersion" mit 0 Argument(en):  "Ausnahme beim Aufrufen von "createHTTPRequest" mit 6 Argument(en):  "Der Wert "Ssl3,Tls,Tls11,Tls12" kann aufgrund von ungültigen Enumerationswerten nicht in  den Typ "System.Net.SecurityProtocolType" konvertiert werden. Geben Sie einen der folgenden Enumerationswerte an, und versuchen Sie es erneut. Mögliche Enumerationswerte sind "Ssl3, Tls".""`

On Windows 7 only deprecated SSL/TLS versions are supported and if one restricts (in this case apache) the protocol usage like this `SSLProtocol             all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1` things will fail... So, with an `SSLProtocol all` directive the installer will work i.e. the problem can be boiled down on the usage of "proper" ssl versions.

**Comment by LordHepipud** [comment]
I think this issue is dicussed. For the handling, I updated the landing page of GitHub of the documenation to hint to this issue.
