### ISSUE TITLE
Suggestion: Set directory permissions when changing service account

### ISSUE THREAD

**Issue by rustyricky** [LordHepipud/icinga2-powershell-module#75]
There are some permissions that need to be set for the Icinga 2 Windows service to work in a different user context than the default, as discussed in this issue: https://github.com/Icinga/icinga2/issues/6266
It could be useful for the PowerShell module to either set the permissions automatically when selecting a different service account or alerting the user to check these permissions.

**Comment by LordHepipud** [comment]
Thank you very much for this. I will definately look into this, as the module should take care of that.

When I understood the issue correctly, giving full rights to the Service user to

```
C:\ProgramData\icinga2\etc
```

resolves the issue?

**Comment by rustyricky** [comment]
Yes exactly. 
The service account should receive permission to read and execute within C:\Program Files\ICINGA2 by being a member of the local users group. I'm not sure whether C:\ProgramData\icinga2 is writable through that, too, so there might be permissions to bet set on that directory, too.
In any case inheritance is disabled on C:\ProgramData\icinga2\etc, so the permissions need to be set there explicitly.

**Comment by NeverUsedID** [comment]
Would be a nice enhancement :)

"etc" was not enough on my side.

I use this snipped to set the permissions:

```
$acl = Get-Acl C:\ProgramData\icinga2
$AccessRule = New-Object System.Security.AccessControl.FileSystemAccessRule("COMPANY\monitoringUser", 'Modify', 'ContainerInherit,ObjectInherit', 'None', 'Allow')
$acl.SetAccessRule($AccessRule)
$acl | Set-Acl C:\ProgramData\icinga2
```

**Comment by LordHepipud** [comment]
As we are moving forward with Icinga for Windows and the PowerShell Framework, we will not continue on this issue.
