### ISSUE TITLE
Feature Request detecion of VMware Time Synchronization

### ISSUE THREAD

**Issue by Wintermute2k6** [LordHepipud/icinga2-powershell-module#76]
## Current Behavior
No Time Synchronization detection at all, which leads to possible double time sync enabling on windows systems -> which leads to jumping system time and therefore agent disconnects

## Expected Behavior
Detection of VMware Time Synchronization Service during agent install via powershell script -> this could open a small warning Dialog with the VMware kbase article with the advice to just enable one timesync.

Eases error diagnostics on strange agent disconnects.

**Comment by LordHepipud** [comment]
As we are moving forward with Icinga for Windows and the PowerShell Framework, we will not continue on this issue.
