### ISSUE TITLE
Parameter -DownloadUrl is overwriten by empty Director setting

### ISSUE THREAD

**Issue by R-Sommer** [LordHepipud/icinga2-powershell-module#79]
The value of the parameter -DownloadUrl is replaced although **Source Path** in Director (commit d69c5a7cc7c6c2ed32056e175fa5aef6b05e02d5) is empty

I'd assume Line 2778: `if (($argumentPos + 2) -le $item.Length) {` is intended to avoid this behaviour. However, the $item.length is 1 byte longer as expected:

$item
download_url: 

$item.Length
15

$item + "x"
download_url: x

$argumentPos
12

[byte][char]$item[13]
32

[byte][char]$item[14]
13

[byte][char]$item[15]
0

**Comment by LordHepipud** [comment]
I see, this is definately an issue here. I'm not quite sure now if the Director should prevent from sending empty values, but in addition the PowerShell Module should also skip this.

I will have a look on this. Thank you for the report.

**Comment by LordHepipud** [comment]
This should be fixed with the latest master, as local arguments are now preferred instead of Director Self-Service arguments
