### ISSUE TITLE
parameterizable mainlog feature

### ISSUE THREAD

**Issue by Gammenon** [LordHepipud/icinga2-powershell-module#81]
# Current Behaviour
main-log object hard coded

# Expected Behaviour
main-log controllable with parameter 

# Details
By default, the main-log section is hard coded inside the powershell module.
because there right now no option to limit/rotate the logfile count or size it is pretty dangerous to enable the main log on windows systems. The default path points to drive c: and because of no size limit the log could swell uncontrolled. In our case the clients server connection was not trusted an therefore there were many log entries in a short time  (about 500MB/day).

For this reason we out commented the part with the log in the psm for now.

/* Enable our default main logger feature to write log output. */
/* outcommented in psm due to missing opportunity to limit log size - 25.09.18 */
/*
object FileLogger "main-log" {
  severity = "information"
  path = LocalStateDir + "/log/icinga2/icinga2.log"
}
*/

Thought about it in a lager scale there is not just the need to enable or disable this with a parameter, there is as well the need for a log configuration like issued in here:
https://github.com/Icinga/icinga2/issues/6634
https://github.com/Icinga/icinga2/issues/4815

From my perspective i would appreciate as a first step a parameter to enable or disable the logging as a whole. I would prefer this over the possibility to control this via constants (or as additional option).

For the future an depending on the realization of the log config as well something like "mainlog_count" (number of files) and "mainlog_filesize" (for every file defined with count) to control the retention.

**Comment by LordHepipud** [comment]
Thank you for the issue. I will have a look on this on how to achieve the requirements.

**Comment by LordHepipud** [comment]
I just push this to the master. The logging is by default enabled and has to be disabled by using

```powershell
-IcingaDisableLogging
```
