### ISSUE TITLE
Add options for self-register details

### ISSUE THREAD

**Issue by lazyfrosch** [LordHepipud/icinga2-powershell-module#83]
We should allow to be configured:

* display_name
* address
* address6

So this can be set from the agent, and is not hard-coded.

**Comment by LordHepipud** [comment]
Thanks for the issue. The address of the Agent is currently being discovered, but I'm sure this can be improved.

By using the Self-Service API from the Director we will have to discuss this, as the Director is right now very restrictive on which parameters as passed.

I would have no problem to implement all 3 options as additional components. Maybe we can discuss this once im back in the office in December?

**Comment by lazyfrosch** [comment]
I noticed that this comes from Director's self-service API as set:

    director_host_object           {"address":"&ipaddress&","display_name":"&hostname&"}

@R-Sommer is mainly interested in two things:

* Using a custom display_name
* Using FQDN instead of IP as address

**Comment by LordHepipud** [comment]
For the display name we could add another argument option if not already present - not quite sure at the moment.

If we modify the Director, we can replace

```
director_host_object           {"address":"&ipaddress&","display_name":"&hostname&"}
```

with

```
director_host_object           {"address":"&fqdn.lowerCase&","display_name":"&hostname&"}
```

For this we could add a Self-Service configuration in the director, if the IP should be discovered by the module or if the FQDN should be used.

The available placeholders are defined [here](https://github.com/Icinga/icinga2-powershell-module/blob/master/doc/31-Placeholders.md)

**Comment by LordHepipud** [comment]
Re-Checked the module: The display name can not yet be set by an argument, but this could be added.
If the argument is not set, the current behaviour will be used.

This seems to be a valid option for me.

**Comment by lazyfrosch** [comment]
I don't really like the cross reference between Director and Powershell here.

When we add `display_name` to the Director returned `director_host_object` it will need the latest Powershell Script as well...

**Comment by LordHepipud** [comment]
I would not add display_name to the Director, only the option to determine if we wish to use the IP-Address or the FQDN.

The Display Name would be set as argument for the PowerShell directly, without the director interfearing here.

By using this entire construct without the Director Self-Service API, it is yet already possible to modify the output, as described in this [Example](https://github.com/Icinga/icinga2-powershell-module/blob/master/doc/30-Examples.md#basic-icinga-installation-with-host-creation-and-deployment).

This will however require User / Password auth for the moment. Maybe we can adjust the script, allowing users to modify the `DirectorHostObject` themself even by using the Self-Service API.

Arguments which are forbidden to be set, are simply skipped by the Director anyway.

```powershell
-DirectorHostObject   '{"object_name":"&hostname_placeholder&","object_type":"object","vars":{"os":"Windows"},"imports":["Icinga Agent"],"address":"&fqdn.lowerCase&","display_name":"My Custom Display Name"}' `
```

Arguments such as vars and imports are dropped, which was the reason the module does not allow this for the moment, to not confuse users why certain things are not set.

**Comment by lazyfrosch** [comment]
There is a big feature gap and security difference between self-service and regular API.

We still should allow basic local configuration of properties that the self-service API would accept.

E.g. you can manually modify the script to set a proper display_name (ignoring `director_host_object`) and Director will accept it.

**Comment by LordHepipud** [comment]
Allright, so what we could do is the following by adding two new arguments (oh gosh...)

`-HostDisplayName`

In case it is set, it will used as display name for the host. If not, the current mechanism applies

`-UseFQDNAddress`

This will set the `address` part to the hosts FQDN. As we already figured out in another ticket, we can pretty correctly fetch the real FQDN, allowing us to use it at this point. In case the FQDN does not apply, we will fallback to the IP Address (as it is right now) and will prompt with a warning that the host is not part of a domain.

What do you think?

**Comment by lazyfrosch** [comment]
Let's have a look on this when you return from vacation :wink:

**Comment by LordHepipud** [comment]
Discussed this with @lazyfrosch 

We will remove the **display_name** by default and no longer provide this argument in first place.
It can however be set with a new argument called

```
-HostDisplayName
```

allowing users to specify it manually or with custom PowerShell functions.

In addition we will add an argument called

```
-UseFQDNAddress
```

to ensure that the FQDN is used as address instead of IPv4/IPv6

**Comment by LordHepipud** [comment]
As we are moving forward with Icinga for Windows and the PowerShell Framework, we will not continue on this issue.
