### ISSUE TITLE
Make results of -DumpIcingaConfig available as object

### ISSUE THREAD

**Issue by brettfire** [LordHepipud/icinga2-powershell-module#87]
I'm looking into a way to mass-deploy the agent, and part of making the process idempotent would seemingly involve avoiding running the installer if the agent and icinga is already installed on a host. I'm looking through the source and options, and I didn't see an option for this. The closest piece of useful code I found was the `-DumpIcingaConfig` switch. The output at first seems to be slightly useful: 
```
Notice: Using Icinga version "", setting certificate directory to "C:\ProgramData\icinga2\etc\icinga2\pki"
Warning: Icinga 2 Agent does not seem to be installed on the system
Notice: Icinga 2 Agent is not installed on the system. No configuration to dump.
```
However, it appears that `properties` and `cfg` objects are still dumped. I was thinking it would be nice if either one of these objects contained an attribute that indicated that the agent and/or icinga2 was missing, or if the script returned some sort of other value. As it stands, the log output is not particularly useful to another script attempting to decide if it should run the installer or not, as it utilizes `write-host`, which only writes to the console. I believe the introduction of the 6 different streams in psv5 would allow  me to capture the output of `write-host` from the information stream (6) using something like `Icinga2AgentModule -DumpIcingaConfig 6>&1`. The issue is that not all of my boxes are up to date with psv5. So it looks like I would possibly be stuck with relying on the file logging facility of your script, and checking the output of that. Any thoughts on the matter? Perhaps I'm missing something? I could write my own checks, but it seems like your script is 90% there.

**Comment by LordHepipud** [comment]
Hello and thank you for the issue.

Do you simply require a solution to detect if the Agent is installed on certain systems and how the configuration is done?

Right now the debug output is only returned, but it should be no problem to store it within a variable which can be returned as output later for debugging.

Is that what your intention is about?

**Comment by brettfire** [comment]
> Hello and thank you for the issue.
> 
> Do you simply require a solution to detect if the Agent is installed on certain systems and how the configuration is done?
> 
> Right now the debug output is only returned, but it should be no problem to store it within a variable which can be returned as output later for debugging.
> 
> Is that what your intention is about?

Yes, I would like to detect if the agent is installed and icinga is installed, just so I do not attempt to reinstall every time the task runs. If there is a preferable way to do this, let me know. Thanks.

**Comment by LordHepipud** [comment]
What do you mean with

`so I do not attempt to reinstall every time the task runs`

The agent should not get installed every time. The script is just checking if there are any required config changes and if your version installed is the intended version defined (either over Self-Service API or manuall specification.

**Comment by brettfire** [comment]
> What do you mean with
> 
> `so I do not attempt to reinstall every time the task runs`
> 
> The agent should not get installed every time. The script is just checking if there are any required config changes and if your version installed is the intended version defined (either over Self-Service API or manuall specification.

Well, with everything already installed, if I run this command:
```
Import-Module Icinga2Agent
$icinga = Icinga2AgentModule `
  -DirectorUrl       'https://myicinga.com/director/' `
  -DirectorAuthToken '12345' `
  -IcingaEnableDebugLog `
  -InstallAgentVersion '2.10.2' `
  -FetchAgentFQDN `
  -RunInstaller
```
I get this output, which looks to me like quite a few things are being done:
```
Notice: Started script run...
Notice: Reading host api token "123456" from "C:\ProgramData\icinga2\etc\icinga2\icing
adirector.token"
Notice: Connected successfully to Icinga Director Self-Service API over stored host token.
Notice: Setting internal Agent Name to "test.server.com"
Notice: Trying to fetch Host IP-Address for hostname: test.server.com
Notice: Setting IP 10.0.1.69 as primary IP for this host for all requests. Access it with &ipaddress& for all JSON reque
sts.
Notice: Transforming Agent Name to test.server.com
Notice: Flushing content of "C:\ProgramData\icinga2\var\lib\icinga2\api"
Notice: Stopping the Icinga 2 Service...
Notice: Icinga 2 service has been stopped.
Notice: Using Icinga version "2.10.2", setting certificate directory to "C:\ProgramData\icinga2\etc\icinga2\pki"
Notice: Found Icinga 2 Agent version 2.10.2 installed at "C:\Program Files\ICINGA2\"
Notice: Icinga 2 Agent is up-to-date. Nothing to do.
Notice: Host is already registered within Icinga Director.
Notice: Fetched ticket "12345" from Icinga Director
Notice: Icinga 2 certificates already exist. Nothing to do.
Warning: Default icinga2.conf backup detected. Skipping backup
Notice: Writing icinga2.conf to "C:\ProgramData\icinga2\etc\icinga2\"
Notice: Icinga 2 configuration check successfull.
Notice: Trying to enable debug log for Icinga 2...
Notice: Icinga 2 debug log has been enabled
Notice: Writing icinga2.conf to "C:\ProgramData\icinga2\etc\icinga2\"
Notice: Trying to install Icinga 2 Agent Firewall Rule for port 5665
Notice: Icinga 2 Agent Firewall Rule already installed. Trying to remove it to add it again...
Notice: Icinga 2 Agent Firewall Rule has been removed. Re-Adding now...
Notice: Icinga 2 Agent Firewall Rule successfully installed for port 5665
Notice: Trying to install and configure NSClient++ from "C:\Program Files\ICINGA2\sbin\NSCP.msi"
Notice: NSClient++ is already installed on the system.
Notice: NSClient++ Firewall Rule is not installed
Notice: NSClient++ Service is not installed
Notice: Restarting service icinga2
Notice: Icinga 2 Agent successfully restarted.
```

**Comment by LordHepipud** [comment]
I see.

```
Notice: Flushing content of "C:\ProgramData\icinga2\var\lib\icinga2\api"
```

Because you have defined Flush API Directory within the Self-Service API, the service is stopped, the Directory flushed and the service started again. This can be resolved by disabling the Flushing of the API Directory (should only be required for upgrades / downgrades.

```
Notice: Writing icinga2.conf to "C:\ProgramData\icinga2\etc\icinga2\"
Notice: Icinga 2 configuration check successfull.
Notice: Trying to enable debug log for Icinga 2...
Notice: Icinga 2 debug log has been enabled
Notice: Writing icinga2.conf to "C:\ProgramData\icinga2\etc\icinga2\"
```

This part is however weird. The script is writing the config, then enabling debug log to write the config again. This shouldn't happen as this would only be one step to write the config. In general once the debug log is enabled, the script should not touch the config at all.

Once you re-run the script, the only "changing" part should be the flushing of the config directory and the restart, which can be resolved by disabling the `Flush Api Directory` within the Icinga Director.

```
Notice: Trying to install Icinga 2 Agent Firewall Rule for port 5665
Notice: Icinga 2 Agent Firewall Rule already installed. Trying to remove it to add it again...
Notice: Icinga 2 Agent Firewall Rule has been removed. Re-Adding now...
Notice: Icinga 2 Agent Firewall Rule successfully installed for port 5665
```

I will try to figure out a way to make this more static. In case the Firewall Rule does exist and the port is correct, the rule should not be touched. Right now I'm deleting and re-adding the rule, as the listen port for Icinga 2 from 5665 could change to another one. I'm sure this can be improved, shouldn't harm active connections however or interrupt the service.

So in general the only problem I see here actually is the config writing part, which will trigger a restart every time - which shouldn't happen if you run the script and re-run it again. The config should not be touched and the service not restared, allowing you to run the script multiple times without modifying anything.

**Comment by brettfire** [comment]
## Install with Flush Config Disabled
Here's what I get when re-running the script with flush config disabled:
```
PS > $icinga = Icinga2AgentModule `
>>   -DirectorUrl       'https://monitor.com/director/' `
>>   -DirectorAuthToken 'xxxxxxxxxxxxxxxxx' `
>>   -IcingaEnableDebugLog `
>>   -InstallAgentVersion '2.10.2' `
>>   -FetchAgentFQDN `
>>   -RunInstaller
>>
Notice: Started script run...
Notice: Reading host api token "xxxxxxxxxxxxxxxx" from "C:\ProgramData\icinga2\etc\icinga2\icing
adirector.token"
Notice: Connected successfully to Icinga Director Self-Service API over stored host token.
Notice: Setting internal Agent Name to "my.server.com"
Notice: Trying to fetch Host IP-Address for hostname: my.server.com
Notice: Setting IP 10.0.1.69 as primary IP for this host for all requests. Access it with &ipaddress& for all JSON reque
sts.
Notice: Transforming Agent Name to my.server.com
Notice: Using Icinga version "2.10.2", setting certificate directory to "C:\ProgramData\icinga2\etc\icinga2\pki"
Notice: Found Icinga 2 Agent version 2.10.2 installed at "C:\Program Files\ICINGA2\"
Notice: Icinga 2 Agent is up-to-date. Nothing to do.
Notice: Host is already registered within Icinga Director.
Notice: Fetched ticket "xxxxxxxxxxxxxxxxxxxxx" from Icinga Director
Notice: Icinga 2 certificates already exist. Nothing to do.
Warning: Default icinga2.conf backup detected. Skipping backup
Notice: Writing icinga2.conf to "C:\ProgramData\icinga2\etc\icinga2\"
Notice: Icinga 2 configuration check successfull.
Notice: Trying to enable debug log for Icinga 2...
Notice: Icinga 2 debug log has been enabled
Notice: Writing icinga2.conf to "C:\ProgramData\icinga2\etc\icinga2\"
Warning: Icinga 2 Agent Firewall Rule will not be installed.
Notice: Trying to install and configure NSClient++ from "C:\Program Files\ICINGA2\sbin\NSCP.msi"
Notice: NSClient++ is already installed on the system.
Notice: NSClient++ Firewall Rule is not installed
Notice: NSClient++ Service is not installed
Notice: Restarting service icinga2
Notice: Icinga 2 Agent successfully restarted.
```

So indeed, it seems that not much is done in the way of changes now, except for restarting icinga. Although it seems like from your response that icinga should not be restarted. Maybe this is a bug in the script? If you could address that, then I would probably feel comfortable running this on a schedule in production. At least that way, the script will ensure that all parts of the solution are always installed and running; a config management tool of sorts (we aren't running saltstack or anything similar at this time). 

## Install with Host Existing from AD Import
Next, I attempted to run the script with the host already existing from a director import from AD (the template is now the agent template). It seems that there was an issue generating the certificate:
```
PS > $icinga = Icinga2AgentModule `
>>   -DirectorUrl       'https://monitor.com/director/' `
>>   -DirectorAuthToken 'xxxxxxxx' `
>>   -IcingaEnableDebugLog `
>>   -InstallAgentVersion '2.10.2' `
>>   -FetchAgentFQDN `
>>   -RunInstaller
>>
Notice: Started script run...
Notice: Connected successfully to Icinga Director Self-Service API over API token.
Notice: Setting internal Agent Name to "my.server.com"
Notice: Trying to fetch Host IP-Address for hostname: my.server.com
Notice: Setting IP 10.0.1.69 as primary IP for this host for all requests. Access it with &ipaddress& for all JSON reque
sts.
Notice: Transforming Agent Name to my.server.com
Notice: Using Icinga version "", setting certificate directory to "C:\ProgramData\icinga2\etc\icinga2\pki"
Warning: Icinga 2 Agent does not seem to be installed on the system
Notice: Downloading Icinga 2 Agent Binary from "https://packages.icinga.com/windows/Icinga2-v2.10.2-x86_64.msi"
Warning: Icinga 2 Agent Installer verification disabled.
Notice: Installing Icinga 2 Agent
Notice: Icinga 2 Agent installed.
Notice: Using Icinga version "2.10.2", setting certificate directory to "C:\ProgramData\icinga2\etc\icinga2\pki"
Notice: Found Icinga 2 Agent version 2.10.2 installed at "C:\Program Files\ICINGA2\"
Notice: Removing downloaded Icinga 2 Agent installer
Notice: Creating host "my.server.com" over API token inside Icinga Director.
Notice: Writing host API-Key "xxxxxxxxxxxxxxxx" to "C:\ProgramData\icinga2\etc\icinga2\icingadir
ector.token"
Notice: Successfully fetched configuration for this host over Self-Service API.
Notice: Fetched ticket "xxxxxxxxxxxxxxxxxxxx" from Icinga Director
Notice: Generating Host certificates required by Icinga 2
Notice: information/base: Writing private key to 'C:\ProgramData\icinga2\etc\icinga2\pki\my.server.com.key'.

information/base: Writing X509 certificate to 'C:\ProgramData\icinga2\etc\icinga2\pki\my.server.com.crt'.
Notice: Storing Icinga 2 certificates
Notice: information/cli: Retrieving X.509 certificate for 'monitor.com:5665'.

 Subject:     CN = monitor.com
 Issuer:      CN = Icinga CA
 Valid From:  Nov 16 21:32:31 2018 GMT
 Valid Until: Nov 12 21:32:31 2033 GMT
 Fingerprint: 4B 08 39 EF 45 5A BA 06 27 20 36 3C 1E 27 2E 3E E5 A9 11 23

***
*** You have to ensure that this certificate actually matches the parent
*** instance's certificate in order to avoid man-in-the-middle attacks.
***

information/pki: Writing certificate to file 'C:\ProgramData\icinga2\etc\icinga2\pki\trusted-master.crt'.
Notice: Certificate fingerprint: "4B0839EF455ABA062720363C1E272E3EE5A91123"
Warning: CA fingerprint validation disabled
Notice: Requesting Icinga 2 certificates
Fatal: Exception calling "generateCertificates" with "0" argument(s): "information/cli: Writing CA certificate to file '
C:\ProgramData\icinga2\etc\icinga2\pki\ca.crt'.
"ritical/cli: !!! Invalid ticket for CN 'my.server.com'.
######## The script encountered several errors during run ########
Fatal: Exception calling "generateCertificates" with "0" argument(s): "information/cli: Writing CA certificate to file '
C:\ProgramData\icinga2\etc\icinga2\pki\ca.crt'.
"ritical/cli: !!! Invalid ticket for CN 'my.server.com'.
```
## Firewall Rule Option
As for the firewall rule option, I'm not even sure how that rule ended up in the firewall, because I have not been using the firewall rule switch. Possibly from a very early test, and the agent would just look for it and reinstall it? I removed the rule, and tried testing to see when it was installed (we manage our own firewall rules via GPO so don't have a need for this, but I'm still curious), and could not get it to re-install the rule. I tried the `-AgentAddFirewallRule` switch, but the script reports `Warning: Icinga 2 Agent Firewall Rule will not be installed.`. I'm also wondering when the rule is actually necessary. Would it be when we have the master set to connect to the agent? Is that preferable? As you can see in the other issue I raised (#88), I had some serious issues with allowing the host to connect to the agents. So would I be correct in assuming that no incoming firewall rule is necessary if I'm having the agents connect to the master? Some clarity on the master-agent connection would be great (had trouble finding much in the documentation on that).

**Comment by LordHepipud** [comment]
Thank you for the tests.

Indeed, the first one is an issue which I have to track down. Which version are you running of the module?

**Certificates**

Do the names actually match? So is the name generated by the PowerShell Module identical to the name of the host within the AD?

**Firewall**

By using the Director Self-Service API, the rule is automaticly added in case the Master is configured to connect to the Agent.

**Comment by brettfire** [comment]
> Thank you for the tests.
> 
> Indeed, the first one is an issue which I have to track down. Which version are you running of the module?

I don't see a version number in the module's code anywhere but I would assume it's v1.2.4, as I've grabbed the module fairly recently.

> **Certificates**
> 
> Do the names actually match? So is the name generated by the PowerShell Module identical to the name of the host within the AD?

The only difference was that the original name was all lowercase, and the new name generated by the script was all uppercase.

**Comment by LordHepipud** [comment]
Allright - thank you very much. I will start some investigation there on why this occures.

For the naming: Both names have to match each other, because the Icinga token for the SSL certificate is generated based on the name. So different namings mean different outputs.
You can tell the script to user loewercase for the name by adjusting the setting within the Icinga Director. Once the name from the PowerShell output matches the name from the AD, the certificate generation will work as expected.

**Comment by brettfire** [comment]
> Allright - thank you very much. I will start some investigation there on why this occures.
> 
> For the naming: Both names have to match each other, because the Icinga token for the SSL certificate is generated based on the name. So different namings mean different outputs.
> You can tell the script to user loewercase for the name by adjusting the setting within the Icinga Director. Once the name from the PowerShell output matches the name from the AD, the certificate generation will work as expected.

Understood. The certificate generation is now working. I've documented this on our internal wiki. Thanks again 👍

![image](https://user-images.githubusercontent.com/5559465/51003816-384bf580-1506-11e9-9e15-1fc60f6666c9.png)

**Comment by LordHepipud** [comment]
As we are moving forward with Icinga for Windows and the PowerShell Framework, we will not continue on this issue.
