### ISSUE TITLE
Installation fails in various ways when host already exists in icinga

### ISSUE THREAD

**Issue by brettfire** [LordHepipud/icinga2-powershell-module#88]
So I'm not sure how exactly icinga and this script as a whole are supposed to behave when a host I'm attempting to install on already exists in icinga. My overall aim here is to have director import hosts from active directory for basic ping checks. For windows hosts, I'd like to use this script along with a GPO and possibly a scheduled task to deploy the agent automatically. The issue I've encountered during my testing of this scenario are the following:

- Installation failure if the host exists in icinga, both with an existing and new agent install, with existing meaning re-running the following code:
```
Import-Module Icinga2Agent
$icinga = Icinga2AgentModule `
  -DirectorUrl       'https://xxxxx/director/' `
  -DirectorAuthToken 'xxxxxx' `
  -IcingaEnableDebugLog `
  -InstallAgentVersion '2.10.2' `
  -FetchAgentFQDN `
  -RunInstaller
```
- This script does not seem to detect and/or deal with the failure too well. Log lines relating to the error only have a "notice" severity level.

When attempting a fresh install (with host existing in icinga), the script reports the following:
```
Notice: Fetched ticket "ERROR: The host "nb-old.us.x.com" is not an agent" from Icinga Director
```

When attempting to reinstall over an existing installation, without uninstalling first, **REGARDLESS** of the host existing in icinga or not, the script reports the following:
```
Notice: Host is already registered within Icinga Director.
Notice: Fetched ticket "ERROR: Got invalid API key "xxxxx"" from Icinga Director
```

I'm not sure if there are some things I missed in the documentation, but I haven't been able to find much while searching for others attempting to use the script in the same scenario, and I also have not been able to find anything relating to the "Got invalid API key" error. Anyone care to lend some clarity to the situation?

**Comment by LordHepipud** [comment]
Hello and thank you for the issue.

In general this doc part would cover your need: https://github.com/Icinga/icinga2-powershell-module/blob/master/doc/20-Automation.md

Besides one small adjustment: In order to make this process work, your host template has to be set as Agent template.

In general it helps to import the `generic-host` template into an `generic-agent` template for example, enabling the Self-Service API capabilities.

I have made a video on this (which is German), but the steps should be easy to re-produce: https://youtu.be/V5o-LHGQEB4?t=850

Actually this should make sure you got a valid API key (from the template) the host registers to - regardless if this is a new or existing host. Just the template has to be set correctly for this, which can lso be achieved for your Import and Sync Rules to assign Windows-Hosts the new Agent template.

I hope this helps.

**Comment by brettfire** [comment]
> Hello and thank you for the issue.
> 
> In general this doc part would cover your need: https://github.com/Icinga/icinga2-powershell-module/blob/master/doc/20-Automation.md
> 
> Besides one small adjustment: In order to make this process work, your host template has to be set as Agent template.
> 
> In general it helps to import the `generic-host` template into an `generic-agent` template for example, enabling the Self-Service API capabilities.
> 
> I have made a video on this (which is German), but the steps should be easy to re-produce: https://youtu.be/V5o-LHGQEB4?t=850
> 
> Actually this should make sure you got a valid API key (from the template) the host registers to - regardless if this is a new or existing host. Just the template has to be set correctly for this, which can lso be achieved for your Import and Sync Rules to assign Windows-Hosts the new Agent template.
> 
> I hope this helps.

So I did not watch the video (it's a bit long and I don't speak any German, although I have owned 3 Audi's at this point 😁), but I did change my sync rule to import the "Icinga Agent" host template for all hosts imported from AD: 
![image](https://user-images.githubusercontent.com/5559465/50881546-f3ae4600-13af-11e9-8f95-9c8b0b00743f.png)

The agent template is currently in use on 219 hosts. Note that currently none of them actually have an agent installed yet. Here is what the agent template looks like: 
```
template Host "Icinga Agent" {
    check_command = "hostalive"
    max_check_attempts = "3"
    check_interval = 1m
    retry_interval = 30s
}
```
Here are the agent/zone settings:
![image](https://user-images.githubusercontent.com/5559465/50881535-ebeea180-13af-11e9-907a-2225ae8f8efd.png)

Now the majority of these hosts are up (205 up / 14 down). The VM running the setup is not starved for resources at all, but after having these hosts import the agent template, the icinga2 API is so sluggish that it is basically unresponsive. Running something such as `curl -k -s -u root:xxxx -H "Accept: application/json" 'https://localhost:5665/v1/config/packages?pretty=1'` just hangs for minutes on end before eventually returning. Attempting to render a config from director fails with a startup message of `Unknown, still waiting for config check outcome` and trying to load the deployments page shows `CURL ERROR: Operation timed out after 3001 milliseconds with 0 out of 0 bytes received` at the top. 

I was previously able to make the API responsive again by manually clearing out the package files, restarting icinga2, then using the http api to delete the director config package. I will continue testing more tomorrow, but I did not have this issue before I started importing the agent template (I was using a standard non-agent template with the same default ping check).

Note that I'm running icinga v2.10.2 and director v1.6.0. Let me know if you have any ideas. I'll try my best to follow along with the video, since I am very interested in your windows infrastructure plugin. It looks great 😉.

**Comment by LordHepipud** [comment]
Thank you for the positive feedback :)

How is the I/O, Load and RAM usage of the system one you query the API? In case you reach the limit there, it will take some time.
Does the API never respond with the Director or simply taking way too long?

It might help to increase the PHP timeout, allowing it to wait longer for an API response from Icinga.

**Comment by brettfire** [comment]
here's what resource usage looks like: 
![image](https://user-images.githubusercontent.com/5559465/50912441-26802a80-1400-11e9-947a-83df00aec557.png)

I did some testing and it seems the issue happens when "Establish connection" is enabled on the template. I thought that option told the agent to establish the connection to the master, but when I was looking at the debug log, it seemed like the master may have been attempting to connect to the agents. Having that option enabled was causing the API to be unresponsive. Is this intended behavior? And would I be right to assume now that the "Establish Connection" option actually means that the master will attempt to connect to the agents?

**Comment by LordHepipud** [comment]
Yes this tell the master to connect to the Agent. It is in general advised not to have both options set.
So either the Master or the Agent should connect - if both try, this could result in an error.

If the issue still persists otherwise, I would recommend opening an issue for the Icinga 2 project itself, as there is not much the Director of the PowerShell module can do here to resolve this issue.

**Comment by brettfire** [comment]
Ok, as I'm sure you realize, it's quite difficult to wrap one's head around the project for a newcomer. What I'm trying to figure out now is ensuring that the agents are connecting to the master.
I'm checking the agent (endpoint?) logs and see this line: `debug/ApiListener: Not connecting to Endpoint 'monitor.icinga.com' because the host/port attributes are missing.` (monitor.icinga.com being a placeholder for my master server FQDN). I tried looking through the docs for this script to see if there's anything that's missing. Do I need to specify `-ParentEndpoints` and `-ParentZone`? 
How can I ensure that the agent is connecting to the master? I have some agent-based checks that I'm not seeing get completed, whereas I recall when I was testing with the master connecting to the agents, I did see the results of those checks.

**Comment by LordHepipud** [comment]
By using the Self-Service API, these settings are configured automaticly, as the Director knows based on the template where to Agent belongs and which parent it reports to.

If you use the Self-Service API, the option

`Establish connection`

determines if the Agent will connect to the master or the master to the Agent. The correct value for this setting will correctly configure the Agent.

**Comment by brettfire** [comment]
So with some testing, I was able to figure out why the clients/agents don't connect to the master. When installing via the script, the icinga2.conf file is written with the master server endpoint like this: 
```
object Endpoint "test.master" {

  port = 5665
}
```
Icinga then reports the following repeatedly:
```
[2019-01-11 14:35:28 -0500] debug/ApiListener: Not connecting to Endpoint 'test.master' because the host/port attributes are missing.
[2019-01-11 14:35:28 -0500] debug/ApiListener: Not connecting to Endpoint 'test.host' because that's us.
[2019-01-11 14:35:28 -0500] notice/ApiListener: Current zone master: test.host
[2019-01-11 14:35:28 -0500] notice/ApiListener: Connected endpoints:
```
The only way to get the agent to connect to the master is to add the "host" config line to icinga2.conf on the client like so:
```
object Endpoint "test.master" {
  host = "test.master"
  port = 5665
}
```
Without this, the agent just will never connect. Is there some place to specify this in the director self-service config?

**Comment by brettfire** [comment]
I did some more testing, and peeked at some code in the module. Please see the following:
```
PS > $icinga = Icinga2AgentModule `
  -DirectorUrl       'https://master.test/director/' `
  -DirectorAuthToken 'xxxxxxxxxxxxxxxxxxxx' `
  -IcingaEnableDebugLog `
  -InstallAgentVersion '2.10.2' `
  -FetchAgentFQDN `
  -ParentZone 'master.test' `
  -ParentEndpoints 'master.test' `
  -EndpointsConfig 'master.test;5665' `
PS > $icinga.getendpointconfigurationbyarrayindex()
  host = "master.test"
  port = 5665
PS > $icinga.config('endpoints_config')
master.test;5665
```

Now what is interesting is when I add the `-RunInstaller` argument, the EndpointsConfig seems to get clobbered somehow, and `getendpointconfigurationbyarrayindex()` only outputs the port to my config:
```
PS > $icinga = Icinga2AgentModule `
  -DirectorUrl       'https://master.test/director/' `
  -DirectorAuthToken 'xxxxxxxxxxxxxxxxxxxx' `
  -IcingaEnableDebugLog `
  -InstallAgentVersion '2.10.2' `
  -FetchAgentFQDN `
  -ParentZone 'master.test' `
  -ParentEndpoints 'master.test' `
  -EndpointsConfig 'master.test;5665' `
  -RunInstaller
PS > $icinga.getendpointconfigurationbyarrayindex()

  port = 5665
PS > $icinga.config('endpoints_config')
;5665
```

I'm looking through the code and I don't immediately see any other place where endpoints_config could be overwritten. Any ideas?

**Comment by brettfire** [comment]
So I found through stepping through execution of the script that the endpoints_config was being overwritten by data directly from self service API. I then discovered that the endpoints config in director was missing the endpoint address. Filled that out, boom issue fixed. So my thinking is that the documentation is pretty lacking on what exactly needs to be filled out at a minimum to get things working. Seems like the best place for this specific docs improvement would be to the director project, since this is a director setting. I did not see anywhere in the director docs that I needed to double-check my endpoint config. Let me know your thoughts.

**Comment by LordHepipud** [comment]
Thank you for your detailed testing and the summary - I sadly received no notifications for your replies.
I'm actually aware of the Director settings always overwritting the local configured settings.

How ever, I am not quite sure which would be the best approach. On one hand, local arguments could always win.
On the other hand, I might want to apply something globally, but my local settings forbid that.

@lazyfrosch What do you think about this? Shall we modify the script that local set arguments will ALWAYS win, regardless of what is configured within the Icinga Director?

For documentations: I will discuss internally where the best approach for this should be done and explain more detailed on how everything should be configured.

Sorry again for the long wait.

**Comment by mikewizzz** [comment]
> So I found through stepping through execution of the script that the endpoints_config was being overwritten by data directly from self service API. I then discovered that the endpoints config in director was missing the endpoint address. Filled that out, boom issue fixed. So my thinking is that the documentation is pretty lacking on what exactly needs to be filled out at a minimum to get things working. Seems like the best place for this specific docs improvement would be to the director project, since this is a director setting. I did not see anywhere in the director docs that I needed to double-check my endpoint config. Let me know your thoughts.

 @icanhazpython  I had the exact same issue for hosts that already existed in Icinga. and was scratching my head for a solution until I saw your fix.  I too was missing the endpoint address in Director. After filling that in, problem solved

I ran your powershell cmds and ran it with -DebugMode and initially got the following error for a host that was already in Director . To solve, I had to delete the host in director first then rerun the powershell script . I noticed you had a similar error but maybe there is a more automated way to fix it then manually deleting "bad" hosts from Director 

`icinga_ticket                  ERROR: Got invalid API key "ERROR: The host "xxxx.xxxx.com" has already been registered (IcingaHostSelfServiceForm.php:103)"`

**Comment by LordHepipud** [comment]
Are you using the Self-Service API or all arguments manually? The hosts should either the added or ignored, unless they are either not having a Self-Service Template- or Host-Key configured.

Can you please provide the exact configuration on which the attempt including your used PowerShell arguments fail?

I will test this within my lab and fix both issues here then.

**Comment by LordHepipud** [comment]
This should be resolved by the latest mater
