### ISSUE TITLE
Problems in combination with NSClient++

### ISSUE THREAD

**Issue by stevie-sy** [LordHepipud/icinga2-powershell-module#89]
The powershell module works very well for us. But now we also want to install the nsclient in combination with icinga to use its built-in checks. 

If we use only the Parameter _-InstallNSClient $true_ the installations works fine. But If I add the parameter ...

- _-NSClientAddDefaults $true_ the installations stops with follwing message :
![image](https://user-images.githubusercontent.com/38723488/54194093-bce1d280-44bb-11e9-9d9b-cfe799183db5.png)
This is the dump: 
[92759670-ac8e-4c81-92c4-c451961a5a89.zip](https://github.com/Icinga/icinga2-powershell-module/files/2956825/92759670-ac8e-4c81-92c4-c451961a5a89.zip)

- _-NSClientEnableFirewall $true_ or _-NSClientEnableService $true_ and run the script with the personal admin-user (not with the Windows-network-user) we get following error: 
![image](https://user-images.githubusercontent.com/38723488/54199436-33d19800-44c9-11e9-85f7-29fe07c4ca0e.png)
For comparison: the icinga2 firewall rule is created without error.
![image](https://user-images.githubusercontent.com/38723488/54199528-6da29e80-44c9-11e9-9046-b17dcbd16109.png)
 
An other Point is following: We use the script also to update icinga to a newer version. For that we use the parameter _-AllowUpdates $true_ . That works fine. 
But if NSClient is not fully deinstalled e.g. with the parameter _-RemoveNSClient $true_  and we re-run the script with the arameter _-NSClientAddDefaults $true_ we get this error: 
![image](https://user-images.githubusercontent.com/38723488/54200348-77c59c80-44cb-11e9-9dab-445d54600a50.png)

Operating System: Windows Server 2012 R2 Standard

**Comment by LordHepipud** [comment]
Hello

Thank you for your message. The problem here is sadly not part of the PowerShell module, but with the bundeled NSClient++ coming with Icinga 2.
To get rid of this problem, you will have to download the latest Version of the NSClient++ for x64 Architecture from the NSClient++ Website.

The NSClient++ bundled in this case with Icinga 2 is failing with the INF crash error on x64 systems.

Sadly nothing I can do here.

**Comment by stevie-sy** [comment]
Thanks for the Information. So we hope, that this will work with a new Version from the nsclient with one future icinga Setup file. So for the moment we can Close this
