### ISSUE TITLE
Feature: Add support for auto configuration

### ISSUE THREAD

**Issue by LordHepipud** [LordHepipud/icinga2-powershell-module#9]
Right now each Windows Systems requires plenty of parameters in order to execute the script correctly.
A better solution would be to - in case possible - access the Icinga Director and retreive all required Informations like configuration, Ticket and Icinga 2 version. This will enable the possibilty to partly automate the entire process on plenty of Windows systems.

For the authentication I recommend a token, allowing access to a host objects configuration inside the Director. Access is only possible by the hostname which is send directly by the script to the Director.

**Comment by cbnorman** [comment]
i have modified the script to request the ticket via the api, see below.

##############################

add-type @"
    using System.Net;
    using System.Security.Cryptography.X509Certificates;
    public class TrustAllCertsPolicy : ICertificatePolicy {
        public bool CheckValidationResult(
            ServicePoint srvPoint, X509Certificate certificate,
            WebRequest request, int certificateProblem) {
            return true;
        }
    }
"@
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy

$secpasswd = ConvertTo-SecureString "icinga" -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential ("root", $secpasswd)

$client = $env:computername.ToLower()
$cn = @{ "cn" = "$client"}
$body = $cn | ConvertTo-Json

$results = (Invoke-WebRequest -Method Post -Uri 'https://master.fqdn:5665/v1/actions/generate-ticket' -Body $body -Headers @{"Accept"="application/json"} -Credential $mycreds -UseBasicParsing).content | ConvertFrom-Json
$ticket = $results.results[0].ticket

#################################

$icinga = Icinga2AgentModule `
    -AgentName       $client `
    -Ticket          $ticket `
    -ParentZone      'master' `

**Comment by LordHepipud** [comment]
Missed to add commit 7a26b2c7fb050691dbabae3f363906b076c7939e, which applies the entire Director automation

**Comment by LordHepipud** [comment]
Implementation done. You will require Icinga Director 1.4.x or later for this feature. The new Director should be available soon.
