### ISSUE TITLE
Add http timeout as a parameter 

### ISSUE THREAD

**Issue by sciolto** [LordHepipud/icinga2-powershell-module#95]
Sometimes it takes more than 6 seconds to establish a HTTPs connection to the Icinga Director, it would be useful to determine timeout as a command line parameter, like so:

```
Icinga2AgentModule `
	-DirectorUrl       'https://icinga/director/'    `
	-DirectorAuthToken 'XXXXXXXXXXXXXXXXXXXXX' 	`
	-RunInstaller `
	-IgnoreSSLErrors `
	-Timeout 40000
```

At the moment the only way is to edit line 681 of the PS Module  https://github.com/Icinga/icinga2-powershell-module/blob/b93aea04462f52c6c7ec14e9aafa820c7c8fb932/Icinga2Agent/Icinga2Agent.psm1#L681

**Comment by LordHepipud** [comment]
Sounds like a great improvement. I will add this during next week.
Thanks for the input !
