### ISSUE TITLE
Do not set display_name property

### ISSUE THREAD

**Issue by log1-c** [LordHepipud/icinga2-powershell-module#97]
Hi,

I’m using the Icinga2 Powershell Module to deploy the Icinga2 Agent with the Director Self-service API.
One thing that bugs me is that the Display name of the host object always is set to the FQDN.
The host name is set, as defined in the self-service api settings, to the non-FQDN name.

I tried deleting , `"display_name": "{0}"` from line 2526, but that didn’t make any difference.

self-service api settings:
![image](https://user-images.githubusercontent.com/24474580/73082116-1cc14c00-3ec9-11ea-8a61-d999c7082470.png)

Is this a problem with the module or with the Icinga Director (or the self-service API)?

**Comment by LordHepipud** [comment]
Sorry for the late response. I believe the Director is always forcing the `display_name`.
You could try to override the `-DirectorHostObject` argument.

```powershell
-DirectorHostObject '{"object_name":"&hostname_placeholder&", "address":"&hostname_placeholder&"}'
```

Does this work?
